name: Publish GPT CT2 Docker image

on: workflow_dispatch

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Docker image
        run: |
          docker build --target ct2_python -t ct2_gpt:latest -t docker.pkg.github.com/ubiqus/lm_autocomplete/ct2_gpt:1.0.0 -f  docker/Dockerfile .

      - name: Push Docker image
        run: |
          docker push docker.pkg.github.com/ubiqus/lm_autocomplete/ct2_gpt:1.0.0
