name: Publish GPT CT2 Docker image

on: workflow_dispatch

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Docker images
        run: |
          docker build --target builder -t CT2_GPT:latest -t docker.pkg.github.com/ubiqus/lm_autocomplete/CT2_GPT:1.0.0 .

      # - name: Login to DockerHub
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Docker images
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   run: |
      #     ./docker/build_all.sh ${GITHUB_REF##*/v} 1
